spring.application.name=premier-zone

# Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/pl_stats
spring.datasource.username=${PL_STATS_DB_USERNAME:postgres}
spring.datasource.password=${PL_STATS_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
